Feature: Asymmetric Key Auth
openware/gotrue pull request #2
Opened 2021-10-08 12:36 UTC by dpatsora

2021-10-10 10:44 UTC, dpatsora reviewed
Add test cases for RSA JWT

2021-10-10 10:44 UTC, dpatsora commented on api/user.go
> +	fmt.Printf("Claims aud: %+v\n", claims)
Remove

2021-10-10 10:44 UTC, dpatsora commented on migrations/20211006231400_create_keys_table.up.sql
> +);
new line

2021-10-10 10:44 UTC, dpatsora commented on models/asymmetric_key.go
> +const challengeExpirationDuration = 30 * time.Minute
challengeTokenExpirationDuration

2021-10-10 10:44 UTC, dpatsora commented on models/asymmetric_key.go
> +	log.Infof("Equal tokens bytes: %v", bytes.Equal([]byte(a.ChallengeToken.String()), []byte("c2918781-fa53-44b1-8a0f-7da323e6fcec")))
Remove

2021-10-10 10:44 UTC, dpatsora commented on models/asymmetric_key.go
> +	log.Infof("Equal signatures: %v", rawSignature == "0x84be2bca9f4ab3ffa5158f0ab857987ad5e286a4b32f98c22c6d74659cff9726777ca74f7469c03b08301cbe3a1c381ece2c57249cfc6e4a0584dcff4b28d73b1c")
Remove

2021-10-10 10:44 UTC, dpatsora commented on models/asymmetric_key.go
> +	// https://github.com/ethereum/go-ethereum/blob/55599ee95d4151a2502465e0afc7c47bd1acba77/internal/ethapi/api.go#L442
Add more comments

2021-10-10 10:44 UTC, dpatsora commented on models/asymmetric_key.go
> +// If key satisfies conditions, nil error is returned
nil is returned

2021-10-10 10:44 UTC, dpatsora commented on models/errors.go
> +// AsymmetricKeyNotFoundError represents when a refresh token is not found.
Remove

2021-10-12 10:43 UTC, mnaichuk requested changes

2022-03-03 10:20 UTC, closed without merging