feature: added first user as superadmin
openware/gotrue pull request #4
Opened 2022-03-04 08:41 UTC by eliot-blankenberg

Signed-off-by: eliot-blankenberg <eblankenberg@openware.center>

2022-03-07 05:17 UTC, dpatsora commented on api/asymmetric_login_test.go
> +func (ts *SignupTestSuite) TestNotFirstSignIn() {
Not clear if the feature is enabled in the test
```
ts.Config.FirstUserSuperAdmin = true
```

2022-03-07 05:40 UTC, dpatsora commented on api/asymmetric_signin.go
> +			}
I would move this logic into (a *API) signupNewUser


```
	err = conn.Transaction(func(tx *storage.Connection) error {
		var terr error
		if terr = tx.Create(user); terr != nil {
			return internalServerError("Database error saving new user").WithInternalError(terr)
		}
		if config.FirstUserSuperAdmin && first {
				terr = user.SetRole(tx, "superadmin")
			} else {
			terr = user.SetRole(tx, config.JWT.DefaultGroupName); terr != nil {
			return internalServerError("Database error updating user").WithInternalError(terr)
		}
			}
	
		if terr = triggerEventHooks(ctx, tx, ValidateEvent, user, instanceID, config); terr != nil {
			return terr
		}
		return nil
	})
	if err != nil {
		return nil, err
	}

	return user, nil
```

2022-03-07 05:41 UTC, dpatsora commented on api/asymmetric_signin.go
> +			}
smth like this

Also models.IsFirstUser is a bit misleading here, as at this moment we don't have user.
I would rename to models.AnyUser or smth like this.

2022-03-07 05:42 UTC, dpatsora requested changes
In general, well done. Tests are good. Please, move the logic into a.signupNewUser, so the logic will be shared between all the endpoints.

2022-03-07 07:21 UTC, dpatsora requested changes

2022-03-07 07:21 UTC, dpatsora commented on models/user.go
> +func AnyUser(tx *storage.Connection) (bool, error) {
AnyUser should return true if userCount != 0

2022-03-07 07:33 UTC, dpatsora requested changes

2022-03-07 07:33 UTC, dpatsora commented on api/signup.go
> +		exist_user, terr := models.AnyUser(tx)
exist_user  -> userExist

2022-03-07 07:33 UTC, dpatsora commented on models/user.go
> +		return true, err
return false, err

2022-03-07 07:42 UTC, dpatsora approved these changes

2022-03-08 09:07 UTC, mnaichuk approved these changes

2022-03-08 09:08 UTC, merged